import os
# Variables
ANCHO = 1200
ALTO = 700
FPS = 25
VIDASINICIALES = 3

RUTAFUENTESENCABEZADOS = os.path.join(
    'Recursos', 'Tipografía', 'SF Distant Galaxy.ttf')
COLORFUENTE = (255, 215, 0)
COLORWARNING = (220, 30, 0)
TAMAÑOMARGENESPARTIDA = 40
GROSORMARGENES = 5

# configuración niveles

NUMERONIVELES = 1
TIEMPO1ERNIVEL = 2
TIEMPOSIGUIENTENIVEL = 1.5
VELOCIDADINICIALOBJETOS = [10, 15]
PUNTOSATERRIZAJE = [20, 100]

# Puntos Naves
PUNTOSNAVE = [9, 22, 16]

# Ruta base de datos
RUTABASEDEDATOS = os.path.join('TheQuest', 'Data', 'Records.db')
NUMERORECORS = 5
